M48
; DRILL file {KiCad (7.0.0)} date Sun Feb 19 19:08:36 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-19T19:08:36+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1142
%
G90
G05
T1
X0.7989Y-2.7862
X0.8002Y-0.9452
X1.6969Y-2.7835
X1.698Y-0.9441
T0
M30
